### ISSUE TITLE
Racer icons does not reposition when a player quits

### ISSUE THREAD

**Issue by vikthortt** [LukeGarrigan/hacktober-race#32]
# Description

If a player leaves the game (e.g. closes window) the rest of the players stop seeing said player icon but the space where (s)he was is still there

# Image
![pre - user drops](https://user-images.githubusercontent.com/5291622/66265464-87e0f880-e7dc-11e9-91c3-04279c339175.PNG)
![pos - user drops](https://user-images.githubusercontent.com/5291622/66265467-8dd6d980-e7dc-11e9-8933-249910ce3f3c.PNG)

**Comment by LukeGarrigan** [comment]
ahh yes, good find!

Go ahead and tackle this one if you like @vikthortt

**Comment by vikthortt** [comment]
ok, I'll work on it

**Comment by LukeGarrigan** [comment]
There's a bit of an issue with the change merged in:

It is not performing the merge &mdash; in code &mdash; so when you win a race it looks like this:


![image](https://user-images.githubusercontent.com/12545967/66345820-b5e34b80-e948-11e9-89e0-bcad2f3d6776.png)

The problem is this code: 

` existingPlayer.y = playerFromServer.y;`

As this happens every tick it is constantly overriding the UI changes to the player's y position. I think it's best off if we do this processing in the UI, the less *we* render the better 😁

I've made the change here https://github.com/LukeGarrigan/hacktober-race/commit/ffe57376c04b0e39cbfec26185ab8f5af5547a25
